apiVersion: apps/v1
kind: Deployment
metadata:
  name: amqp-urano-deployment
  namespace: planets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amqp-urano
  template:
    metadata:
      labels:
        app: amqp-urano
    spec:
      containers:
        - name: sender
          image: sender-image:latest # Use a tag from the built sender Docker image
        - name: receiver
          ports:
          - containerPort: 9010
---
apiVersion: v1
kind: Service
metadata:
  name: amqp-urano-service
spec:
  ports:
    - port: 9010
  selector:
    app: amqp-urano
---
