name: CI/CD para Flask Python3

on:
  push:
    branches:
      - main
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_HUB_URI: ${{ seu_dockerhub_uri }}
  IMAGE_NAME: ${{ netuno-receiver-microservice }}
  TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configura o ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Instala dependências
      run: |
        pip install -r requirements.txt

# CASO TENHA TESTES, DESCOMENTE AS LINHAS ABAIXO
#    - name: Executa testes
#      run: |
#        python -m unittest discover -s tests

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configura Docker
      uses: docker/setup-buildx-action@v1

    - name: Realiza login no Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        TAG=${{ github.sha }}
        
        # Build da imagem
        docker build -t $IMAGE_NAME:$TAG -f $DOCKER_HUB_URI/$IMAGE_NAME:$TAG .
        
        # Push da imagem
        docker push $DOCKER_HUB_URI/$IMAGE_NAME:$TAG

    - name: Build e envia imagem Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_HUB_URI }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}